[package]
name = "numty"
version = "0.2.0"
entrypoint = "src/exports.typ"
authors = ["Pablo Ruiz Cuevas"]
license = "MIT"
description = "Numeric Typst"
exclude = ["test.typ"]
repository = "https://github.com/PabloRuizCuevas/numty"
categories = ["utility","scripting"]
keywords = ["matrix", "array", "matrices", "math", "numpy", "vector"]
